import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mohit Walia</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Portfolio Site By:&nbsp;
            <code className={styles.code}>Mohit Walia</code>
          </p>
          <div>
            <a
              href="https://mohitwalia.netlify.app/"
              target="_blank"
              rel="noopener noreferrer"
            >
              {' '}
              <Image
                src="/shape.png"
                alt="Vercel Logo"
                className={styles}
                width={100}
                height={100}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/pelton-turbine-wheel.png"
            alt="Next.js Logo"
            width={300}
            height={300}
            priority
          />
          
        </div>

        <div className={styles.grid}>
          <a
            href="https://mohitwalia.netlify.app/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Bio <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              My name is Mohit Walia. I am a full stack web developer having 4 years of experience in Various techonology like wordpress, shopify, Webflow, PHP nextjs, Nodejs from inside to outside.
            </p>
          </a>

          <a
            href="https://mohitwalia.netlify.app/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Techonology <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Wordpress, Shopify, Webflow, Wix, Squarespace, Woocommerce
            </p>
          </a>

          <a
            href="https://mohitwalia.netlify.app/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Languages <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              PHP, JAVASCRIPT, HTML, ReactJs, NextJs, NodeJs, Mysql, jQuery
            </p>
          </a>

          <a
            href="https://mohitwalia.netlify.app/"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Contact <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              +91 7018629215<br />
              mohitw420@gmail.com
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
